In [26]:
import datacommons_pandas as dc
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import pandas as pd
import dotenv

d_vals = dotenv.dotenv_values("../.env")
dc.set_api_key(d_vals['DC_API_KEY'])

In [27]:
usa = 'country/USA'

states = dc.get_places_in([usa], 'State')[usa]
df_state = dc.build_multivariate_dataframe(states, ['Count_Person', 'Median_Age_Person'])
df_state

          Count_Person  Median_Age_Person
place
geoId/01       4997675               39.3
geoId/02        735951               35.0
geoId/04       7079203               38.1
geoId/05       3006309               38.3
geoId/06      39455353               37.0
geoId/08       5723176               37.1
geoId/09       3605330               41.0
geoId/10        981892               41.1
geoId/11        683154               34.3
geoId/12      21339762               42.3
geoId/13      10625615               37.1
geoId/15       1453498               39.6
geoId/16       1811617               36.8
geoId/17      12821813               38.5
geoId/18       6751340               37.9
geoId/19       3179090               38.3
geoId/20       2932099               37.0
geoId/21       4494141               39.0
geoId/22       4657305               37.4
geoId/23       1357046               44.7
geoId/24       6148545               38.9
geoId/25       6991852               39.6
geoId/26      10062512               39.8
geoId/27       5670472               38.2
geoId/28       2967023               37.8
geoId/29       6141534               38.8
geoId/30       1077978               40.0
geoId/31       1951480               36.7
geoId/32       3059238               38.3
geoId/33       1372175               43.0
geoId/34       9234024               40.0
geoId/35       2109366               38.3
geoId/36      20114745               39.2
geoId/37      10367022               39.0
geoId/38        773344               35.2
geoId/39      11769923               39.4
geoId/40       3948136               36.8
geoId/41       4207177               39.6
geoId/42      12970650               40.8
geoId/44       1091949               40.0
geoId/45       5078903               39.8
geoId/46        881785               37.1
geoId/47       6859497               38.8
geoId/48      28862581               35.0
geoId/49       3231370               31.3
geoId/50        641637               42.7
geoId/51       8582479               38.5
geoId/53       7617364               37.9
geoId/54       1801049               42.6
geoId/55       5871661               39.6
geoId/56        576641               38.2
geoId/72       3311274               43.1